export default {
  WELCOME: "خوش آمدید",
  LOGIN: "ورود",
  REGISTER: "ثبت نام",
  HOME: "خانه",
  SETTING_TAB: "صفحه تنظیمات",
  SETTING: "تنظیمات",
  CONTACT_LIST_TAB: "تراکنش‌ها",
  CATEGORY_LIST_TAB: "اشخاص",
  CONTACT_LIST: "لیست‌اشخاص",
  CATEGORY_LIST: "لیست‌تراکنش‌ها",
  CATEGORY: "دسته‌بندی",
  CONTACT: "شخص",
  ACCOUNT: "اطلاعات کاربری",
  EDIT: "ویرایش اطلاعات",
};
